from __future__ import annotations

# Defaults used only when a new endpoint has no saved database setting.
# Stored Open5e keys remain unchanged; these values affect presentation/access only.
DEFAULT_ENDPOINT_SETTINGS: dict[str, dict[str, str]] = {
    "abilitie": {"display": "Ability", "minimum_role": "user"},
    "abilities": {"display": "Ability", "minimum_role": "user"},
    "alignment": {"display": "Alignment", "minimum_role": "user"},
    "alignments": {"display": "Alignment", "minimum_role": "user"},
    "armor": {"display": "Armor", "minimum_role": "user"},
    "background": {"display": "Background", "minimum_role": "user"},
    "backgrounds": {"display": "Background", "minimum_role": "user"},
    "class": {"display": "Class", "minimum_role": "user"},
    "classes": {"display": "Class", "minimum_role": "user"},
    "condition": {"display": "Condition", "minimum_role": "user"},
    "conditions": {"display": "Condition", "minimum_role": "user"},
    "creatureset": {"display": "Creature Set", "minimum_role": "user"},
    "creaturesets": {"display": "Creature Set", "minimum_role": "user"},
    "creaturetype": {"display": "Creature Type", "minimum_role": "user"},
    "creaturetypes": {"display": "Creature Type", "minimum_role": "user"},
    "damagetype": {"display": "Damage Type", "minimum_role": "user"},
    "damagetypes": {"display": "Damage Type", "minimum_role": "user"},
    "document": {"display": "Document", "minimum_role": "user"},
    "documents": {"display": "Document", "minimum_role": "user"},
    "environment": {"display": "Environment", "minimum_role": "user"},
    "environments": {"display": "Environment", "minimum_role": "user"},
    "feat": {"display": "Feat", "minimum_role": "user"},
    "feats": {"display": "Feat", "minimum_role": "user"},
    "gamesystem": {"display": "Game System", "minimum_role": "user"},
    "gamesystems": {"display": "Game System", "minimum_role": "user"},
    "image": {"display": "Image", "minimum_role": "user"},
    "images": {"display": "Image", "minimum_role": "user"},
    "item": {"display": "Item", "minimum_role": "user"},
    "itemcategorie": {"display": "Item Category", "minimum_role": "user"},
    "itemcategories": {"display": "Item Category", "minimum_role": "user"},
    "itemraritie": {"display": "Item Rarity", "minimum_role": "user"},
    "itemrarities": {"display": "Item Rarity", "minimum_role": "user"},
    "itemset": {"display": "Item Set", "minimum_role": "user"},
    "itemsets": {"display": "Item Set", "minimum_role": "user"},
    "language": {"display": "Language", "minimum_role": "user"},
    "languages": {"display": "Language", "minimum_role": "user"},
    "license": {"display": "License", "minimum_role": "user"},
    "licenses": {"display": "License", "minimum_role": "user"},
    "magicitem": {"display": "Magic Item", "minimum_role": "user"},
    "magicitems": {"display": "Magic Item", "minimum_role": "user"},
    "monster": {"display": "Monster", "minimum_role": "user"},
    "creatures": {"display": "Monster", "minimum_role": "user"},
    "publisher": {"display": "Publisher", "minimum_role": "user"},
    "publishers": {"display": "Publisher", "minimum_role": "user"},
    "rule": {"display": "Rule", "minimum_role": "user"},
    "rules": {"display": "Rule", "minimum_role": "user"},
    "ruleset": {"display": "Rule Set", "minimum_role": "user"},
    "rulesets": {"display": "Rule Set", "minimum_role": "user"},
    "service": {"display": "Service", "minimum_role": "user"},
    "services": {"display": "Service", "minimum_role": "user"},
    "size": {"display": "Size", "minimum_role": "user"},
    "sizes": {"display": "Size", "minimum_role": "user"},
    "skill": {"display": "Skill", "minimum_role": "user"},
    "skills": {"display": "Skill", "minimum_role": "user"},
    "species": {"display": "Species", "minimum_role": "user"},
    "spell": {"display": "Spell", "minimum_role": "user"},
    "spells": {"display": "Spell", "minimum_role": "user"},
    "spellschool": {"display": "Spell School", "minimum_role": "user"},
    "spellschools": {"display": "Spell School", "minimum_role": "user"},
    "weapon": {"display": "Weapon", "minimum_role": "user"},
    "weapons": {"display": "Weapon", "minimum_role": "user"},
    "weaponpropertie": {"display": "Weapon Property", "minimum_role": "user"},
    "weaponproperties": {"display": "Weapon Property", "minimum_role": "user"},
}

def endpoint_default(term: str) -> dict[str, str]:
    return DEFAULT_ENDPOINT_SETTINGS.get(term, {"display": term.replace("_", " ").title(), "minimum_role": "user"})
